# Generated by Django 3.1 on 2020-11-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlogdata', '0002_auto_20201105_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandates',
            name='ClientID',
        ),
        migrations.RemoveField(
            model_name='mandates',
            name='RecruiterAssignedTo',
        ),
        migrations.RemoveField(
            model_name='usr_table',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='usr_table',
            name='UserName',
            field=models.TextField(null=True),
        ),
    ]
